import {
  WaterSource,
  WaterOrder,
  WaterReport,
  SubsidyVoucher,
  BulkRequest,
} from './types';

export const ENUGU_AREAS = [
  'Independence Layout',
  'New Haven',
  'Abakpa',
  'Emene',
  'GRA',
  'Thinkers Corner',
  'Ogui',
  'Uwani',
  'Trans Ekulu',
  'Nsukka',
  '9th Mile',
  'Gariki',
  'Achara Layout',
];

export const WATER_SOURCES: WaterSource[] = [
  {
    id: 'src-001',
    name: 'Fresh Water Tanker Co.',
    type: 'tanker',
    area: 'Independence Layout',
    distanceKm: 0.3,
    availableLitres: 8000,
    pricePerLitre: 35,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.8,
    reviewCount: 124,
    etaMinutes: 15,
    lastQualityCheck: '2026-06-16',
    status: 'available',
    coordinates: { lat: 6.45, lng: 7.52 },
    operatorName: 'Chukwu Tankers',
    operatorPhone: '+234-815-123-4567',
    complaintCount: 2,
  },
  {
    id: 'src-002',
    name: 'Crystal Pure Borehole',
    type: 'borehole',
    area: 'New Haven',
    distanceKm: 1.2,
    availableLitres: 15000,
    pricePerLitre: 20,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.6,
    reviewCount: 89,
    lastQualityCheck: '2026-06-15',
    status: 'available',
    coordinates: { lat: 6.42, lng: 7.55 },
    operatorName: 'Eze\'s Borehole Services',
    operatorPhone: '+234-816-456-7890',
    complaintCount: 1,
  },
  {
    id: 'src-003',
    name: 'Abakpa Public Water Point',
    type: 'public_point',
    area: 'Abakpa',
    distanceKm: 2.1,
    availableLitres: 5000,
    pricePerLitre: 10,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.2,
    reviewCount: 156,
    lastQualityCheck: '2026-06-14',
    status: 'available',
    coordinates: { lat: 6.48, lng: 7.58 },
    operatorName: 'Enugu Water Agency',
    complaintCount: 5,
  },
  {
    id: 'src-004',
    name: 'Emene Rapid Water',
    type: 'tanker',
    area: 'Emene',
    distanceKm: 3.5,
    availableLitres: 6000,
    pricePerLitre: 40,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.3,
    reviewCount: 67,
    etaMinutes: 28,
    lastQualityCheck: '2026-06-12',
    status: 'busy',
    coordinates: { lat: 6.38, lng: 7.62 },
    operatorName: 'Speed Water Delivery',
    operatorPhone: '+234-814-789-0123',
    complaintCount: 3,
  },
  {
    id: 'src-005',
    name: 'Government Subsidized Truck',
    type: 'subsidized_truck',
    area: 'New Haven',
    distanceKm: 0.8,
    availableLitres: 20000,
    pricePerLitre: 15,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.9,
    reviewCount: 203,
    etaMinutes: 20,
    lastQualityCheck: '2026-06-17',
    status: 'available',
    coordinates: { lat: 6.41, lng: 7.54 },
    operatorName: 'Enugu State Water Board',
    complaintCount: 0,
  },
  {
    id: 'src-006',
    name: 'GRA Borehole Network',
    type: 'borehole',
    area: 'GRA',
    distanceKm: 4.2,
    availableLitres: 12000,
    pricePerLitre: 22,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.7,
    reviewCount: 95,
    lastQualityCheck: '2026-06-16',
    status: 'available',
    coordinates: { lat: 6.51, lng: 7.48 },
    operatorName: 'GRA Water Solutions',
    operatorPhone: '+234-813-234-5678',
    complaintCount: 1,
  },
  {
    id: 'src-007',
    name: 'Thinkers Corner Public Tap',
    type: 'public_point',
    area: 'Thinkers Corner',
    distanceKm: 1.5,
    availableLitres: 3000,
    pricePerLitre: 12,
    verified: false,
    verificationStatus: 'pending',
    rating: 3.8,
    reviewCount: 34,
    lastQualityCheck: '2026-06-10',
    status: 'offline',
    coordinates: { lat: 6.44, lng: 7.50 },
    operatorName: 'Community Water Council',
    complaintCount: 8,
  },
  {
    id: 'src-008',
    name: 'Ogui Express Water',
    type: 'tanker',
    area: 'Ogui',
    distanceKm: 2.8,
    availableLitres: 7000,
    pricePerLitre: 38,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.5,
    reviewCount: 78,
    etaMinutes: 22,
    lastQualityCheck: '2026-06-17',
    status: 'available',
    coordinates: { lat: 6.46, lng: 7.60 },
    operatorName: 'Ogui Water Logistics',
    operatorPhone: '+234-817-567-8901',
    complaintCount: 2,
  },
  {
    id: 'src-009',
    name: 'Uwani Quality Borehole',
    type: 'borehole',
    area: 'Uwani',
    distanceKm: 3.2,
    availableLitres: 18000,
    pricePerLitre: 19,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.8,
    reviewCount: 142,
    lastQualityCheck: '2026-06-16',
    status: 'available',
    coordinates: { lat: 6.50, lng: 7.65 },
    operatorName: 'Uwani Water Trust',
    operatorPhone: '+234-812-890-1234',
    complaintCount: 0,
  },
  {
    id: 'src-010',
    name: 'Trans Ekulu Municipal Water',
    type: 'public_point',
    area: 'Trans Ekulu',
    distanceKm: 4.5,
    availableLitres: 8000,
    pricePerLitre: 11,
    verified: true,
    verificationStatus: 'verified',
    rating: 4.1,
    reviewCount: 112,
    lastQualityCheck: '2026-06-15',
    status: 'available',
    coordinates: { lat: 6.53, lng: 7.62 },
    operatorName: 'Enugu Municipal Authority',
    complaintCount: 4,
  },
];

export const SAMPLE_ORDERS: WaterOrder[] = [
  {
    id: 'order-001',
    residentName: 'Joshua Nnadi',
    residentArea: 'New Haven',
    quantityLitres: 1000,
    sourceId: 'src-005',
    sourceName: 'Government Subsidized Truck',
    status: 'delivered',
    price: 15000,
    subsidyApplied: true,
    subsidyAmount: 6000,
    deliveryFee: 500,
    createdAt: '2026-06-17T08:30:00Z',
    estimatedDeliveryTime: '30 mins',
  },
  {
    id: 'order-002',
    residentName: 'Amara Okonkwo',
    residentArea: 'Independence Layout',
    quantityLitres: 500,
    sourceId: 'src-001',
    sourceName: 'Fresh Water Tanker Co.',
    status: 'on_the_way',
    price: 17500,
    subsidyApplied: false,
    subsidyAmount: 0,
    deliveryFee: 800,
    createdAt: '2026-06-17T09:15:00Z',
    estimatedDeliveryTime: '15 mins',
  },
  {
    id: 'order-003',
    residentName: 'Emeka Chukwu',
    residentArea: 'Abakpa',
    quantityLitres: 5000,
    sourceId: 'src-002',
    sourceName: 'Crystal Pure Borehole',
    status: 'accepted',
    price: 100000,
    subsidyApplied: false,
    subsidyAmount: 0,
    deliveryFee: 2500,
    createdAt: '2026-06-17T09:45:00Z',
    estimatedDeliveryTime: '45 mins',
  },
  {
    id: 'order-004',
    residentName: 'Chioma Nwosu',
    residentArea: 'GRA',
    quantityLitres: 250,
    sourceId: 'src-006',
    sourceName: 'GRA Borehole Network',
    status: 'requested',
    price: 5500,
    subsidyApplied: false,
    subsidyAmount: 0,
    deliveryFee: 1200,
    createdAt: '2026-06-17T10:20:00Z',
    estimatedDeliveryTime: '40 mins',
  },
];

export const SAMPLE_REPORTS: WaterReport[] = [
  {
    id: 'report-001',
    type: 'dirty_water',
    area: 'Emene',
    description: 'Water from tanker was brownish and unpleasant smell',
    severity: 'high',
    status: 'reviewing',
    createdAt: '2026-06-17T08:00:00Z',
  },
  {
    id: 'report-002',
    type: 'failed_delivery',
    area: 'Thinkers Corner',
    description: 'Tanker did not arrive within promised time window',
    severity: 'medium',
    status: 'open',
    createdAt: '2026-06-17T07:30:00Z',
  },
  {
    id: 'report-003',
    type: 'broken_pipe',
    area: 'Abakpa',
    description: 'Public water point pipe burst, water leaking',
    severity: 'high',
    status: 'open',
    createdAt: '2026-06-16T14:00:00Z',
  },
  {
    id: 'report-004',
    type: 'overpricing',
    area: 'Emene',
    description: 'Price quoted was ₦50/L but charged ₦70/L at delivery',
    severity: 'medium',
    status: 'reviewing',
    createdAt: '2026-06-16T11:20:00Z',
  },
  {
    id: 'report-005',
    type: 'dry_tap',
    area: 'Nsukka',
    description: 'Public water point has been dry for 3 days',
    severity: 'high',
    status: 'open',
    createdAt: '2026-06-15T16:45:00Z',
  },
  {
    id: 'report-006',
    type: 'fake_tanker',
    area: 'New Haven',
    description: 'Unverified tanker without proper registration',
    severity: 'high',
    status: 'reviewing',
    createdAt: '2026-06-14T09:30:00Z',
  },
];

export const DEMO_SUBSIDY_VOUCHER: SubsidyVoucher = {
  id: 'voucher-demo-001',
  residentName: 'Joshua Nnadi',
  area: 'New Haven',
  discountPercent: 40,
  maxLitres: 1000,
  status: 'active',
  createdAt: '2026-06-01T00:00:00Z',
  expiresAt: '2026-07-01T00:00:00Z',
};

export const SAMPLE_BULK_REQUESTS: BulkRequest[] = [
  {
    id: 'bulk-001',
    area: 'Thinkers Corner',
    street: 'Street 4',
    targetLitres: 10000,
    joinedHouseholds: 23,
    requestedAt: '2026-06-17T10:00:00Z',
    estimatedDeliveryDate: '2026-06-17T14:00:00Z',
    status: 'accepted',
    estimatedCostPerHousehold: 15000,
  },
  {
    id: 'bulk-002',
    area: 'Abakpa',
    street: 'School Avenue',
    targetLitres: 15000,
    joinedHouseholds: 34,
    requestedAt: '2026-06-17T08:30:00Z',
    estimatedDeliveryDate: '2026-06-17T16:00:00Z',
    status: 'on_the_way',
    estimatedCostPerHousehold: 8500,
  },
  {
    id: 'bulk-003',
    area: 'Independence Layout',
    street: 'Unity Estate',
    targetLitres: 5000,
    joinedHouseholds: 12,
    requestedAt: '2026-06-17T09:00:00Z',
    estimatedDeliveryDate: '2026-06-17T12:00:00Z',
    status: 'requested',
    estimatedCostPerHousehold: 12000,
  },
];

export const AREA_DEMAND_MAP: Record<string, number> = {
  'Independence Layout': 45,
  'New Haven': 72,
  'Abakpa': 38,
  'Emene': 28,
  'GRA': 25,
  'Thinkers Corner': 54,
  'Ogui': 31,
  'Uwani': 19,
  'Trans Ekulu': 22,
  'Nsukka': 15,
  '9th Mile': 18,
  'Gariki': 12,
  'Achara Layout': 9,
};

export const AREA_SUPPLY_MAP: Record<string, number> = {
  'Independence Layout': 8,
  'New Haven': 12,
  'Abakpa': 4,
  'Emene': 3,
  'GRA': 6,
  'Thinkers Corner': 2,
  'Ogui': 5,
  'Uwani': 4,
  'Trans Ekulu': 3,
  'Nsukka': 1,
  '9th Mile': 2,
  'Gariki': 1,
  'Achara Layout': 1,
};
